spring:
  application:
    name: PhotoShare-Service
  datasource:
    name: driud
    url: jdbc:mysql://mysql.default:3306/photoshare?useSSL=false&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
      enabled: true
  redis:
    host: redis.default
    port: 6379 #docker redis端口
    timeout: 180
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 0
logging:
  level:
    com.cust.dao: debug
    org.springframework.web: info
mybatis:
  mapper-locations: classpath:mybatis/*.xml

server:
  port: 8080
