apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:5.0.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: redis
spec:
  type: NodePort
  ports:
    - port: 6379
      nodePort: 30003
      targetPort: 6379
  selector:
    app: redis