kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: dev
  name: wechat-pic
  labels:
    usage: wechat-pic
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/home/wxpicture"
    type: DirectoryOrCreate
  storageClassName: wx-pic
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cyka   # 需要修改为发布mysql服务的node节点的hostname
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dev
  name: wechat-pic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: wx-pic
  resources:
    requests:
      storage: 5Gi
#  selector:
#    matchLabels:
#      usage: wechat-pic
