kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: default
  name: commons-mysql
  labels:
    usage: commons-mysql-5.7
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/data/mysql/data-volume"
    type: DirectoryOrCreate
  storageClassName: standard
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cyka   # 需要修改为发布mysql服务的node节点的hostname
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: commons-mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
#  selector:
#    matchLabels:
#      usage: commons-mysql-5.7
